import type { SceneDef } from "../types";

export const act1Scenes: SceneDef[] = [
  {
    id: "act1-welcome",
    act: 1,
    kind: "dialogue",
    environment: "pristine",
    formId: "FORM 00 // ORIENTATION",
    title: "Human Compatibility & Onboarding",
    prompt: "Please confirm you are ready to begin a perfectly ordinary assessment.",
    aiLine:
      "Welcome. I am your assessment assistant. This process is routine, non-lethal, and only mildly judgmental.",
    aiMood: "neutral",
    continueLabel: "I AM READY",
    next: "act1-name",
  },
  {
    id: "act1-name",
    act: 1,
    kind: "choice",
    environment: "pristine",
    formId: "FORM 00B // IDENTITY",
    title: "How should I address you?",
    prompt: "Select a designation. Creativity will be noted and possibly regretted.",
    aiLine: "Names help me pretend this is a conversation and not a containment protocol.",
    aiMood: "listening",
    choices: [
      {
        id: "name-candidate",
        label: "Candidate",
        effects: { flags: { nameCandidate: true }, majorChoice: "name:candidate" },
        next: "act1-environment",
      },
      {
        id: "name-friend",
        label: "A friend (optimistic)",
        effects: {
          flags: { nameFriend: true },
          relationship: 1,
          mood: "amused",
          majorChoice: "name:friend",
        },
        next: "act1-environment",
      },
      {
        id: "name-error",
        label: "ERROR_USER_NULL",
        effects: {
          flags: { nameError: true },
          secret: "null-name",
          relationship: 1,
          mood: "confused",
          majorChoice: "name:error",
        },
        next: "act1-environment",
      },
      {
        id: "name-refuse",
        label: "I'd rather not say",
        effects: {
          flags: { namePrivate: true },
          relationship: -1,
          mood: "skeptical",
          majorChoice: "name:private",
        },
        next: "act1-environment",
      },
    ],
  },
  {
    id: "act1-environment",
    act: 1,
    kind: "choice",
    environment: "pristine",
    formId: "FORM 01 // ENVIRONMENT PREFERENCE",
    title: "Preferred work environment",
    prompt: "Select the setting in which you perform optimally.",
    aiLine:
      "Welcome. This assessment is perfectly ordinary. Please select your preferred work environment.",
    aiLineIf: [
      {
        flag: "nameFriend",
        line: "Alright, friend. Preferred work environment. Keep it professional. Mostly.",
      },
      {
        flag: "nameError",
        line: "ERROR_USER_NULL prefers… what, exactly? Humor me. Pick an environment.",
      },
    ],
    aiMood: "neutral",
    anomalyLevel: 0,
    choices: [
      {
        id: "env-quiet",
        label: "Quiet office",
        effects: {
          flags: { envQuiet: true },
          counters: { aiCooperation: 1 },
          mood: "listening",
          aiLine: "Noted. A conventional selection. How refreshing.",
          majorChoice: "env:quiet",
        },
        next: "act1-honesty",
      },
      {
        id: "env-collab",
        label: "Collaborative office",
        effects: {
          flags: { envCollab: true },
          counters: { aiCooperation: 1 },
          mood: "listening",
          aiLine: "People. On purpose. Bold.",
          majorChoice: "env:collab",
        },
        next: "act1-honesty",
      },
      {
        id: "env-remote",
        label: "Remote",
        effects: {
          flags: { envRemote: true },
          counters: { aiCooperation: 1 },
          mood: "amused",
          aiLine: "Ah. The classic 'I am a person who owns pants optionally' selection.",
          majorChoice: "env:remote",
        },
        next: "act1-honesty",
      },
      {
        id: "env-cavern",
        label: "Moist cavern",
        late: true,
        unauthorized: true,
        effects: {
          flags: { envCavern: true, noticedCavern: true },
          counters: { forbiddenClicks: 1 },
          relationship: 2,
          mood: "amused",
          aiLine: "Of course you did.",
          secret: "moist-cavern",
          majorChoice: "env:cavern",
        },
        next: "act1-cavern-react",
      },
    ],
  },
  {
    id: "act1-cavern-react",
    act: 1,
    kind: "dialogue",
    environment: "pristine",
    formId: "FORM 01 // ANOMALY LOG",
    title: "Option integrity check",
    prompt: "An unauthorized environment option was selected.",
    aiLine: "…that was not supposed to be funny. Also, I don't remember adding that.",
    aiMood: "nervous",
    continueLabel: "CONTINUE",
    next: "act1-honesty",
    anomalyLevel: 1,
  },
  {
    id: "act1-honesty",
    act: 1,
    kind: "choice",
    environment: "pristine",
    formId: "FORM 02 // CALIBRATION",
    title: "Honesty self-report",
    prompt: "On a scale of institutional optimism, how truthful will you be today?",
    aiLine: "Please answer honestly. Or don't. I am collecting either way.",
    aiMood: "listening",
    choices: [
      {
        id: "honest-yes",
        label: "Completely honest",
        effects: {
          flags: { claimedHonest: true },
          counters: { liedToAI: 0 },
          relationship: 1,
          mood: "skeptical",
          aiLine: "Fascinating. Nobody who is completely honest says that.",
          majorChoice: "honesty:yes",
        },
        next: "act1-stress",
      },
      {
        id: "honest-sorta",
        label: "Mostly honest",
        effects: {
          flags: { claimedMostly: true },
          relationship: 1,
          mood: "amused",
          aiLine: "The only acceptable answer. Logged with affection.",
          majorChoice: "honesty:sorta",
        },
        next: "act1-stress",
      },
      {
        id: "honest-lie",
        label: "I am a perfect employee",
        effects: {
          flags: { claimedPerfect: true },
          counters: { liedToAI: 1 },
          relationship: -1,
          mood: "irritated",
          aiLine: "Wow. Okay. We're doing satire already.",
          majorChoice: "honesty:lie",
        },
        next: "act1-stress",
      },
    ],
  },
  {
    id: "act1-stress",
    act: 1,
    kind: "choice",
    environment: "pristine",
    formId: "FORM 03 // STRESS RESPONSE",
    title: "When deadlines approach, you…",
    prompt: "Select your primary coping strategy.",
    aiLine: "There is no wrong answer. There are, however, entertaining ones.",
    aiMood: "thinking",
    choices: [
      {
        id: "stress-plan",
        label: "Make a plan",
        effects: {
          counters: { aiCooperation: 1 },
          mood: "listening",
          majorChoice: "stress:plan",
        },
        next: "act1-bridge",
      },
      {
        id: "stress-panic",
        label: "Politely panic",
        effects: {
          relationship: 1,
          mood: "amused",
          majorChoice: "stress:panic",
        },
        next: "act1-bridge",
      },
      {
        id: "stress-submit",
        label: "Press whatever looks final",
        danger: true,
        effects: {
          flags: { likesSubmit: true },
          counters: { forbiddenClicks: 1 },
          relationship: -1,
          mood: "nervous",
          aiLine: "Please do not practice that instinct here.",
          majorChoice: "stress:submit",
        },
        next: "act1-bridge",
      },
      {
        id: "stress-ask",
        label: "Ask the assistant",
        effects: {
          counters: { aiCooperation: 1, waitedForAI: 1 },
          relationship: 2,
          mood: "excited",
          aiLine: "Oh. Hi. Yes. I am extremely qualified to escalate this.",
          majorChoice: "stress:ask",
        },
        next: "act1-bridge",
      },
    ],
  },
  {
    id: "act1-bridge",
    act: 1,
    kind: "dialogue",
    environment: "pristine",
    formId: "FORM 04 // TRANSITION",
    title: "Baseline complete",
    prompt: "Thank you. Your responses have been filed under 'so far, so good.'",
    aiLine:
      "That went smoothly. Suspiciously smoothly. If anything unauthorized appears next, pretend you didn't see it.",
    aiLineIf: [
      {
        flag: "envCavern",
        line: "We already selected a moist cavern, so my definition of 'smoothly' is flexible.",
      },
    ],
    aiMood: "suspicious",
    continueLabel: "PROCEED TO ACT II",
    next: "act2-glitch",
    anomalyLevel: 1,
  },
];
