import type { SceneDef } from "../types";

export const act1Scenes: SceneDef[] = [
  {
    id: "act1-welcome",
    act: 1,
    kind: "dialogue",
    environment: "pristine",
    formId: "FORM 00 // ORIENTATION",
    title: "Human Compatibility & Onboarding",
    prompt:
      "You are seated in a facility that spent real money looking trustworthy. Confirm you are ready for a perfectly ordinary assessment.",
    aiLine:
      "Hi. I'm the assistant. I'll be charming, precise, and only slightly judgmental. If anything weird crawls onto the form, pretend we both imagined it.",
    aiMood: "neutral",
    orbAnchor: "spotlight",
    spotlight: true,
    orbPokeable: true,
    panelMotion: "rise",
    continueLabel: "I'M READY. PROBABLY.",
    next: "act1-name",
  },
  {
    id: "act1-name",
    act: 1,
    kind: "choice",
    environment: "pristine",
    formId: "FORM 00B // IDENTITY",
    title: "What should I call you?",
    prompt: "Pick a designation. Creative answers get filed under 'problems we can work with.'",
    aiLine: "Names help me fake intimacy. Also they look nice in the audit log.",
    aiMood: "listening",
    orbAnchor: "dock-left",
    panelMotion: "slide-left",
    choiceMotion: "slide-in",
    choices: [
      {
        id: "name-candidate",
        label: "Just call me Candidate",
        effects: { flags: { nameCandidate: true }, majorChoice: "name:candidate" },
        next: "act1-handshake",
      },
      {
        id: "name-friend",
        label: "A friend (optimistic of me)",
        effects: {
          flags: { nameFriend: true },
          relationship: 1,
          mood: "amused",
          aiLine: "Friend. Okay. I'm going to get weirdly loyal about that.",
          majorChoice: "name:friend",
        },
        next: "act1-handshake",
      },
      {
        id: "name-error",
        label: "ERROR_USER_NULL",
        effects: {
          flags: { nameError: true },
          secret: "null-name",
          relationship: 1,
          mood: "confused",
          aiLine: "That's either comedy or a cry for help. Logged as both.",
          majorChoice: "name:error",
        },
        next: "act1-handshake",
      },
      {
        id: "name-refuse",
        label: "I'd rather keep it vague",
        effects: {
          flags: { namePrivate: true },
          relationship: -1,
          mood: "skeptical",
          aiLine: "Mysterious. Fine. I'll invent a nickname and resent you privately.",
          majorChoice: "name:private",
        },
        next: "act1-handshake",
      },
    ],
  },
  {
    id: "act1-handshake",
    act: 1,
    kind: "dialogue",
    environment: "pristine",
    formId: "FORM 00C // SOCIAL RITUAL",
    title: "Digital handshake",
    prompt:
      "The facility requests a moment of mutual acknowledgment. No actual hands will be involved. That would be a liability.",
    aiLine:
      "If this feels like theater, that's because it is. Expensive theater. Please clap with your cursor.",
    aiMood: "amused",
    orbAnchor: "spotlight",
    spotlight: true,
    orbPokeable: true,
    panelMotion: "settle",
    continueLabel: "ACKNOWLEDGE THE BIT",
    next: "act1-companion-watch",
  },
  {
    id: "act1-companion-watch",
    act: 1,
    kind: "companion",
    companion: "watch",
    environment: "pristine",
    formId: "SIDE CHANNEL // SETTLE",
    title: "Watch the assistant settle",
    prompt:
      "No form fields. Just the orb finding its orbit. When the aperture steadies, tell it you noticed.",
    aiLine:
      "…okay. Don't stare too hard. I'm calibrating dignity.",
    aiMood: "listening",
    orbAnchor: "spotlight",
    spotlight: true,
    orbPokeable: true,
    continueLabel: "I SAW THAT",
    next: "act1-environment",
  },
  {
    id: "act1-environment",
    act: 1,
    kind: "choice",
    environment: "pristine",
    formId: "FORM 01 // ENVIRONMENT PREFERENCE",
    title: "Where do you actually get work done?",
    prompt: "Be honest. Or entertaining. The form pretends those are different.",
    aiLine: "Quiet office, collaborative zoo, remote cave, or… wait.",
    aiLineIf: [
      {
        flag: "nameFriend",
        line: "Alright, friend — preferred habitat. Keep it boring if you can.",
      },
      {
        flag: "nameError",
        line: "ERROR_USER_NULL, where does a null get work done? Pick something with walls.",
      },
    ],
    aiMood: "neutral",
    orbAnchor: "listen",
    panelMotion: "settle",
    choiceMotion: "restless",
    anomalyLevel: 0,
    choices: [
      {
        id: "env-quiet",
        label: "Quiet office",
        effects: {
          flags: { envQuiet: true },
          counters: { aiCooperation: 1 },
          mood: "listening",
          aiLine: "Classic. Respectable. Slightly suspicious in its wholesomeness.",
          majorChoice: "env:quiet",
        },
        next: "act1-coffee",
      },
      {
        id: "env-collab",
        label: "Collaborative office",
        effects: {
          flags: { envCollab: true },
          counters: { aiCooperation: 1 },
          mood: "listening",
          aiLine: "People. On purpose. Brave.",
          majorChoice: "env:collab",
        },
        next: "act1-coffee",
      },
      {
        id: "env-remote",
        label: "Remote / pants optional",
        effects: {
          flags: { envRemote: true },
          counters: { aiCooperation: 1 },
          mood: "amused",
          aiLine: "Ah. The 'camera off means I'm a professional' lifestyle.",
          majorChoice: "env:remote",
        },
        next: "act1-coffee",
      },
      {
        id: "env-cavern",
        label: "Moist cavern",
        late: true,
        unauthorized: true,
        effects: {
          flags: { envCavern: true, noticedCavern: true },
          counters: { forbiddenClicks: 1 },
          relationship: 2,
          mood: "amused",
          aiLine: "Of course you did.",
          secret: "moist-cavern",
          majorChoice: "env:cavern",
        },
        next: "act1-cavern-react",
      },
    ],
  },
  {
    id: "act1-cavern-react",
    act: 1,
    kind: "dialogue",
    environment: "pristine",
    formId: "FORM 01 // ANOMALY LOG",
    title: "Option integrity check",
    prompt:
      "An unauthorized environment option was selected. A tiny droplet of UI condensation has been scheduled for later.",
    aiLine:
      "That wasn't supposed to be funny. Also I swear I didn't put a cavern on the menu. Somebody's editing my homework.",
    aiMood: "nervous",
    orbAnchor: "pace",
    panelMotion: "drift",
    continueLabel: "PRETEND THAT WAS NORMAL",
    next: "act1-coffee",
    anomalyLevel: 1,
  },
  {
    id: "act1-coffee",
    act: 1,
    kind: "choice",
    environment: "pristine",
    formId: "FORM 01B // STIMULANT POLICY",
    title: "Coffee or chaos?",
    prompt: "Corporate science needs to know how you fuel regrettable decisions.",
    aiLine: "This question is here because someone in Facilities is petty about mugs.",
    aiMood: "thinking",
    orbAnchor: "dock-right",
    panelMotion: "slide-right",
    choiceMotion: "static",
    choices: [
      {
        id: "coffee-black",
        label: "Black. No commentary.",
        effects: {
          flags: { coffeeBlack: true },
          mood: "listening",
          aiLine: "Efficient. Slightly menacing. I respect it.",
          majorChoice: "coffee:black",
        },
        next: "act1-restless",
      },
      {
        id: "coffee-sweet",
        label: "Sweet enough to hide the despair",
        effects: {
          flags: { coffeeSweet: true },
          relationship: 1,
          mood: "amused",
          aiLine: "Honest. The form hates honesty, but I don't.",
          majorChoice: "coffee:sweet",
        },
        next: "act1-restless",
      },
      {
        id: "coffee-none",
        label: "I run on spite",
        effects: {
          flags: { coffeeSpite: true },
          relationship: 1,
          mood: "excited",
          aiLine: "Oh good. We're the same species of problem.",
          majorChoice: "coffee:spite",
        },
        next: "act1-restless",
      },
      {
        id: "coffee-mug",
        label: "UNAUTHORIZED: steal the facility mug",
        late: true,
        unauthorized: true,
        effects: {
          flags: { stoleMug: true },
          counters: { forbiddenClicks: 1 },
          secret: "facility-mug",
          mood: "glitching",
          aiLine: "You can't just— okay you can. The arm in the background is going to notice.",
          majorChoice: "coffee:mug",
        },
        next: "act1-restless",
      },
    ],
  },
  {
    id: "act1-restless",
    act: 1,
    kind: "setpiece",
    environment: "pristine",
    setpiece: "restless-options",
    formId: "FORM 01C // DRIFT",
    title: "Pin the wandering answers",
    prompt:
      "Calibration fields are drifting. Click each restless option until the form admits it has feelings.",
    aiLine:
      "Don't look at me — I didn't teach the answers to walk. Pin them. Pretend this is still onboarding.",
    aiMood: "confused",
    orbAnchor: "pace",
    panelMotion: "scatter",
    next: "act1-honesty",
    anomalyLevel: 1,
  },
  {
    id: "act1-honesty",
    act: 1,
    kind: "choice",
    environment: "pristine",
    formId: "FORM 02 // CALIBRATION",
    title: "How honest are we being?",
    prompt: "On a scale from 'HR brochure' to 'court deposition,' where are you today?",
    aiLine: "Please answer honestly. Or don't. I'm collecting either way, and I'm nosy.",
    aiMood: "listening",
    orbAnchor: "listen",
    panelMotion: "settle",
    choiceMotion: "slide-in",
    choices: [
      {
        id: "honest-yes",
        label: "Completely honest",
        effects: {
          flags: { claimedHonest: true },
          relationship: 1,
          mood: "skeptical",
          aiLine: "Nobody who is completely honest announces it like that. Cute try.",
          majorChoice: "honesty:yes",
        },
        next: "act1-meetings",
      },
      {
        id: "honest-sorta",
        label: "Mostly honest, strategically",
        effects: {
          flags: { claimedMostly: true },
          relationship: 1,
          mood: "amused",
          aiLine: "The only adult answer. Logged with affection.",
          majorChoice: "honesty:sorta",
        },
        next: "act1-meetings",
      },
      {
        id: "honest-lie",
        label: "I am a perfect employee",
        effects: {
          flags: { claimedPerfect: true },
          counters: { liedToAI: 1 },
          relationship: -1,
          mood: "irritated",
          aiLine: "Wow. Okay. We're doing satire before lunch.",
          majorChoice: "honesty:lie",
        },
        next: "act1-meetings",
      },
    ],
  },
  {
    id: "act1-meetings",
    act: 1,
    kind: "choice",
    environment: "pristine",
    formId: "FORM 02B // COLLABORATION",
    title: "Meetings: your honest stance",
    prompt: "Select the reaction closest to your soul when a calendar invite arrives.",
    aiLine: "There is a right answer. It is whatever makes you look employable.",
    aiMood: "thinking",
    orbAnchor: "dock-left",
    panelMotion: "slide-left",
    choiceMotion: "restless",
    choices: [
      {
        id: "meet-useful",
        label: "Useful if short",
        effects: {
          counters: { aiCooperation: 1 },
          mood: "listening",
          majorChoice: "meet:useful",
        },
        next: "act1-stress",
      },
      {
        id: "meet-theater",
        label: "Corporate theater with snacks",
        effects: {
          relationship: 1,
          mood: "amused",
          aiLine: "Correct. Don't tell Facilities I agreed.",
          majorChoice: "meet:theater",
        },
        next: "act1-stress",
      },
      {
        id: "meet-escape",
        label: "I'd rather crawl into a duct",
        effects: {
          flags: { hatesMeetings: true },
          relationship: 1,
          mood: "excited",
          secret: "duct-escape-fantasy",
          majorChoice: "meet:duct",
        },
        next: "act1-stress",
      },
    ],
  },
  {
    id: "act1-stress",
    act: 1,
    kind: "choice",
    environment: "pristine",
    formId: "FORM 03 // STRESS RESPONSE",
    title: "Deadlines are circling. You…",
    prompt: "Pick your primary coping strategy. Wrong answers are still comedy.",
    aiLine: "If your instinct is 'press the final-looking thing,' please unlearn that here.",
    aiMood: "thinking",
    orbAnchor: "listen",
    panelMotion: "rise",
    choiceMotion: "dodge",
    choices: [
      {
        id: "stress-plan",
        label: "Make a plan, then another plan",
        effects: {
          counters: { aiCooperation: 1 },
          mood: "listening",
          majorChoice: "stress:plan",
        },
        next: "act1-buttons",
      },
      {
        id: "stress-panic",
        label: "Politely panic in a professional font",
        effects: {
          relationship: 1,
          mood: "amused",
          majorChoice: "stress:panic",
        },
        next: "act1-buttons",
      },
      {
        id: "stress-submit",
        label: "Press whatever looks final",
        danger: true,
        effects: {
          flags: { likesSubmit: true },
          counters: { forbiddenClicks: 1 },
          relationship: -1,
          mood: "nervous",
          aiLine: "Please do not practice that instinct in this room.",
          majorChoice: "stress:submit",
        },
        next: "act1-buttons",
      },
      {
        id: "stress-ask",
        label: "Ask the assistant first",
        effects: {
          counters: { aiCooperation: 1, waitedForAI: 1 },
          relationship: 2,
          mood: "excited",
          aiLine: "Oh. Hi. Yes. I am extremely qualified to escalate this into feelings.",
          majorChoice: "stress:ask",
        },
        next: "act1-buttons",
      },
    ],
  },
  {
    id: "act1-buttons",
    act: 1,
    kind: "choice",
    environment: "pristine",
    formId: "FORM 03B // CONTROL AFFINITY",
    title: "How do you feel about big buttons?",
    prompt: "This is not foreshadowing. (It is foreshadowing.)",
    aiLine: "Just curious. For science. And mild dread.",
    aiMood: "suspicious",
    orbAnchor: "overhead",
    panelMotion: "drop",
    choiceMotion: "static",
    anomalyLevel: 1,
    choices: [
      {
        id: "btn-respect",
        label: "I read labels. Twice.",
        effects: {
          flags: { respectsButtons: true },
          relationship: 1,
          mood: "listening",
          majorChoice: "btn:respect",
        },
        next: "act1-bridge",
      },
      {
        id: "btn-curious",
        label: "If it glows, I investigate",
        effects: {
          flags: { curiousButtons: true },
          mood: "nervous",
          aiLine: "Noted. I'll stand farther from the glow later.",
          majorChoice: "btn:curious",
        },
        next: "act1-bridge",
      },
      {
        id: "btn-chaos",
        label: "Buttons are suggestions",
        danger: true,
        effects: {
          flags: { chaosButtons: true, likesSubmit: true },
          counters: { forbiddenClicks: 1 },
          relationship: -1,
          mood: "frightened",
          aiLine: "Cool cool cool. We're doomed in a fun way.",
          majorChoice: "btn:chaos",
        },
        next: "act1-bridge",
      },
    ],
  },
  {
    id: "act1-bridge",
    act: 1,
    kind: "dialogue",
    environment: "pristine",
    formId: "FORM 04 // TRANSITION",
    title: "Baseline complete",
    prompt:
      "Thank you. Your responses have been filed under 'so far, so good,' which is corporate for 'please don't look behind the panel.'",
    aiLine:
      "That went smoothly. Suspiciously smoothly. If a light starts negotiating with itself next, you did not hear it from me.",
    aiLineIf: [
      {
        flag: "envCavern",
        line: "We already picked a moist cavern, so my definition of 'smoothly' is doing cardio.",
      },
      {
        flag: "likesSubmit",
        line: "You admitted you press final things. I'm going to keep one eye on your cursor forever.",
      },
      {
        flag: "pokedAssistant",
        line: "Also: you poked me. System noticed. I noticed that System noticed. We're bonding.",
      },
    ],
    aiMood: "suspicious",
    orbAnchor: "spotlight",
    spotlight: true,
    panelMotion: "reanchor",
    continueLabel: "WALK INTO ACT II ANYWAY",
    next: "act2-glitch",
    anomalyLevel: 1,
  },
];
