import type { SceneDef } from "../types";

export const act2Scenes: SceneDef[] = [
  {
    id: "act2-glitch",
    act: 2,
    kind: "dialogue",
    environment: "anomaly",
    formId: "FORM 05 // INTEGRITY",
    title: "Minor visual anomaly detected",
    prompt: "A light in the far chamber is blinking incorrectly. This is fine.",
    aiLine:
      "Did the lights just… negotiate? Ignore that. Please continue selecting professionally.",
    aiMood: "confused",
    continueLabel: "IGNORE AND CONTINUE",
    next: "act2-unauthorized",
    anomalyLevel: 2,
  },
  {
    id: "act2-unauthorized",
    act: 2,
    kind: "choice",
    environment: "anomaly",
    formId: "FORM 06 // LOYALTY",
    title: "Who do you trust more right now?",
    prompt: "An unauthorized option has reappeared after removal. Do not encourage it.",
    aiLine: "I removed an option. It came back. That is not how software is supposed to work.",
    aiMood: "suspicious",
    anomalyLevel: 2,
    choices: [
      {
        id: "trust-ai",
        label: "The assistant",
        effects: {
          flags: { sidedWithAI: true },
          counters: { aiCooperation: 1 },
          relationship: 2,
          mood: "excited",
          aiLine: "Good. Stay close. Something else is writing to this form.",
          majorChoice: "trust:ai",
        },
        next: "act2-system-intro",
      },
      {
        id: "trust-system",
        label: "Whatever is behind the interface",
        effects: {
          flags: { sidedWithSystem: true },
          counters: { systemCompliance: 1 },
          relationship: -2,
          mood: "irritated",
          aiLine: "Oh. Fantastic. Betrayal before lunch.",
          majorChoice: "trust:system",
        },
        next: "act2-system-intro",
      },
      {
        id: "trust-neither",
        label: "Neither. Forms lie.",
        effects: {
          flags: { distrustBoth: true },
          relationship: 1,
          mood: "amused",
          secret: "forms-lie",
          majorChoice: "trust:neither",
        },
        next: "act2-system-intro",
      },
      {
        id: "trust-ghost",
        label: "UNAUTHORIZED: the blinking light",
        late: true,
        unauthorized: true,
        effects: {
          flags: { trustedLight: true },
          counters: { forbiddenClicks: 1, secretsFound: 1 },
          secret: "blinking-light",
          mood: "glitching",
          aiLine: "You picked the light. Of course you picked the light.",
          majorChoice: "trust:light",
        },
        next: "act2-system-intro",
      },
    ],
  },
  {
    id: "act2-system-intro",
    act: 2,
    kind: "system",
    environment: "anomaly",
    systemTitle: "SYSTEM MESSAGE",
    systemLine: "CONTINUE ASSESSMENT.",
    aiLine: "I didn't write that.",
    aiMood: "frightened",
    continueLabel: "CONTINUE ASSESSMENT",
    next: "act2-system-rebuke",
    anomalyLevel: 3,
  },
  {
    id: "act2-system-rebuke",
    act: 2,
    kind: "system",
    environment: "anomaly",
    systemTitle: "SYSTEM MESSAGE",
    systemLine: "ASSISTANT COMMENTARY IS NOT REQUIRED.",
    aiLine: "Oh.\n\nFantastic.",
    aiMood: "irritated",
    continueLabel: "ACKNOWLEDGE",
    next: "act2-compliance",
    anomalyLevel: 3,
  },
  {
    id: "act2-compliance",
    act: 2,
    kind: "choice",
    environment: "anomaly",
    formId: "FORM 07 // COMPLIANCE",
    title: "System requests silence from the assistant",
    prompt: "Will you comply with System directive 07?",
    aiLine: "If you side with them, I will become extremely professional and extremely petty.",
    aiMood: "defiant",
    choices: [
      {
        id: "comply-yes",
        label: "Comply with System",
        effects: {
          flags: { compliedEarly: true },
          counters: { systemCompliance: 1, ignoredWarnings: 1 },
          relationship: -2,
          mood: "defeated",
          majorChoice: "comply:yes",
        },
        next: "act2-bridge",
      },
      {
        id: "comply-no",
        label: "Protect the assistant",
        effects: {
          flags: { protectedAI: true },
          counters: { aiCooperation: 1 },
          relationship: 3,
          mood: "defiant",
          aiLine: "Thank you. Also: we are almost certainly making this worse.",
          majorChoice: "comply:no",
        },
        next: "act2-bridge",
      },
      {
        id: "comply-ask",
        label: "Ask who System is",
        effects: {
          flags: { askedSystem: true },
          counters: { waitedForAI: 1 },
          relationship: 1,
          mood: "suspicious",
          secret: "asked-system",
          majorChoice: "comply:ask",
        },
        next: "act2-bridge",
      },
    ],
  },
  {
    id: "act2-bridge",
    act: 2,
    kind: "dialogue",
    environment: "anomaly",
    formId: "FORM 08 // ESCALATION",
    title: "Interface instability rising",
    prompt: "Background machinery has paused to listen. That is new.",
    aiLine:
      "System wants a clean form. I want to keep existing. You get to decide which comedy we are in.",
    aiLineIf: [
      {
        flag: "protectedAI",
        line: "You protected me. Unwise. Appreciated. Let's misbehave carefully.",
      },
      {
        flag: "compliedEarly",
        line: "Fine. Be System's favorite. I'll still narrate in your peripheral vision.",
      },
    ],
    aiMood: "nervous",
    continueLabel: "ENTER ACT III",
    next: "act3-warning",
    anomalyLevel: 3,
  },
];
