import type { SceneDef } from "../types";

export const act2Scenes: SceneDef[] = [
  {
    id: "act2-glitch",
    act: 2,
    kind: "dialogue",
    environment: "anomaly",
    formId: "FORM 05 // INTEGRITY",
    title: "Minor visual anomaly detected",
    prompt:
      "A light in the far chamber is blinking with intent. Facilities has marked this 'fine.' Facilities is lying.",
    aiLine:
      "Did the lights just… negotiate a union? Ignore that. Keep selecting professionally. I'll panic quietly.",
    aiMood: "confused",
    orbAnchor: "flee",
    panelMotion: "drift",
    continueLabel: "IGNORE AND CONTINUE",
    next: "act2-flicker",
    anomalyLevel: 2,
  },
  {
    id: "act2-flicker",
    act: 2,
    kind: "choice",
    environment: "anomaly",
    formId: "FORM 05B // ATTENTION",
    title: "The blinking light wants a word",
    prompt: "Do you look at it, name it, or pretend corporate lighting has always been sentient?",
    aiLine: "Please don't make friends with the infrastructure. It never ends well in movies.",
    aiMood: "nervous",
    orbAnchor: "overhead",
    panelMotion: "edge",
    choiceMotion: "restless",
    anomalyLevel: 2,
    choices: [
      {
        id: "flicker-ignore",
        label: "I saw nothing",
        effects: {
          flags: { ignoredFlicker: true },
          counters: { ignoredWarnings: 1 },
          mood: "skeptical",
          aiLine: "Cowardice is a valid strategy. Temporarily.",
          majorChoice: "flicker:ignore",
        },
        next: "act2-unauthorized",
      },
      {
        id: "flicker-wave",
        label: "Wave at it like a person",
        effects: {
          flags: { wavedAtLight: true },
          relationship: 1,
          mood: "amused",
          aiLine: "It waved back. I hate that I noticed.",
          majorChoice: "flicker:wave",
        },
        next: "act2-unauthorized",
      },
      {
        id: "flicker-report",
        label: "Report it to… someone",
        effects: {
          flags: { reportedFlicker: true },
          counters: { systemCompliance: 1 },
          mood: "irritated",
          aiLine: "To whom? HR? God? The stamp?",
          majorChoice: "flicker:report",
        },
        next: "act2-unauthorized",
      },
    ],
  },
  {
    id: "act2-unauthorized",
    act: 2,
    kind: "choice",
    environment: "anomaly",
    formId: "FORM 06 // LOYALTY",
    title: "Who do you trust more right now?",
    prompt:
      "An option I deleted came back with better lighting. Do not encourage software that moonlights as a poltergeist.",
    aiLine: "I removed an option. It returned. That is not how code is supposed to work. That's how hauntings work.",
    aiMood: "suspicious",
    orbAnchor: "pace",
    panelMotion: "scatter",
    choiceMotion: "scatter",
    anomalyLevel: 2,
    choices: [
      {
        id: "trust-ai",
        label: "You, the assistant",
        effects: {
          flags: { sidedWithAI: true },
          counters: { aiCooperation: 1 },
          relationship: 2,
          mood: "excited",
          aiLine: "Good. Stay close. Something else is writing into this form like it pays rent.",
          majorChoice: "trust:ai",
        },
        next: "act2-stamp",
      },
      {
        id: "trust-system",
        label: "Whatever's behind the glass",
        effects: {
          flags: { sidedWithSystem: true },
          counters: { systemCompliance: 1 },
          relationship: -2,
          mood: "irritated",
          aiLine: "Oh. Fantastic. Betrayal before we even hit the good set pieces.",
          majorChoice: "trust:system",
        },
        next: "act2-stamp",
      },
      {
        id: "trust-neither",
        label: "Neither. Forms lie for sport.",
        effects: {
          flags: { distrustBoth: true },
          relationship: 1,
          mood: "amused",
          secret: "forms-lie",
          majorChoice: "trust:neither",
        },
        next: "act2-stamp",
      },
      {
        id: "trust-ghost",
        label: "UNAUTHORIZED: the blinking light",
        late: true,
        unauthorized: true,
        effects: {
          flags: { trustedLight: true },
          counters: { forbiddenClicks: 1, secretsFound: 1 },
          secret: "blinking-light",
          mood: "glitching",
          aiLine: "You picked the light. Of course you picked the light.",
          majorChoice: "trust:light",
        },
        next: "act2-stamp",
      },
    ],
  },
  {
    id: "act2-stamp",
    act: 2,
    kind: "setpiece",
    environment: "anomaly",
    setpiece: "authority-stamp",
    formId: "FORM 06B // CERTIFICATION",
    title: "Catch the authority stamp",
    prompt:
      "A rubber APPROVED stamp is skittering across the stage. Stamp it down before it certifies nonsense.",
    aiLine:
      "System brought stationery. Violent stationery. Pin it. I'll pretend this is still a survey.",
    aiMood: "defiant",
    orbAnchor: "loom",
    panelMotion: "pressure",
    next: "act2-duplicate",
    anomalyLevel: 3,
  },
  {
    id: "act2-duplicate",
    act: 2,
    kind: "choice",
    environment: "anomaly",
    formId: "FORM 06C // DUPLICATE",
    title: "This question already asked itself",
    prompt: "The form reprinted a loyalty question with slightly worse manners. Pick a lane.",
    aiLine: "I didn't queue that reprint. If you hear a voice that isn't me, it's not improvisation.",
    aiMood: "frightened",
    orbAnchor: "hide",
    panelMotion: "reanchor",
    choiceMotion: "dodge",
    anomalyLevel: 3,
    choices: [
      {
        id: "dup-assistant",
        label: "Stick with the assistant's version",
        effects: {
          flags: { preferAiCopy: true },
          counters: { aiCooperation: 1 },
          relationship: 1,
          mood: "defiant",
          majorChoice: "dup:ai",
        },
        next: "act2-system-intro",
      },
      {
        id: "dup-system",
        label: "Obey the colder reprint",
        effects: {
          flags: { preferSystemCopy: true },
          counters: { systemCompliance: 1 },
          relationship: -1,
          mood: "defeated",
          majorChoice: "dup:system",
        },
        next: "act2-system-intro",
      },
      {
        id: "dup-both",
        label: "Answer both and confuse the auditors",
        late: true,
        secret: true,
        effects: {
          flags: { answeredBoth: true },
          secret: "double-answer",
          relationship: 2,
          mood: "amused",
          majorChoice: "dup:both",
        },
        next: "act2-system-intro",
      },
    ],
  },
  {
    id: "act2-system-intro",
    act: 2,
    kind: "system",
    environment: "anomaly",
    systemTitle: "SYSTEM MESSAGE",
    systemLine: "CONTINUE ASSESSMENT.",
    aiLine: "I didn't write that.",
    aiMood: "frightened",
    orbAnchor: "flee",
    panelMotion: "drop",
    continueLabel: "CONTINUE ASSESSMENT",
    next: "act2-system-rebuke",
    anomalyLevel: 3,
  },
  {
    id: "act2-system-rebuke",
    act: 2,
    kind: "system",
    environment: "anomaly",
    systemTitle: "SYSTEM MESSAGE",
    systemLine: "ASSISTANT COMMENTARY IS NOT REQUIRED.",
    aiLine: "Oh.\n\nFantastic.",
    aiMood: "irritated",
    orbAnchor: "hide",
    continueLabel: "ACKNOWLEDGE",
    next: "act2-whisper",
    anomalyLevel: 3,
  },
  {
    id: "act2-whisper",
    act: 2,
    kind: "dialogue",
    environment: "anomaly",
    formId: "FORM 06D // SIDE CHANNEL",
    title: "Quietly, while System looks away",
    // Gag allowlist: side-channel may crowd the assistant — fiction owns the bury.
    buryAssistant: true,
    prompt: "The assistant drifts to the edge of the stage and talks like someone sharing a fire exit.",
    aiLine:
      "Okay. Off the record: something above me thinks I'm furniture. If you hear it bark, don't salute unless you mean it.",
    aiLineIf: [
      {
        flag: "sidedWithAI",
        line: "You already picked me once. I'm going to cash that chip later. Softly. Desperately.",
      },
      {
        flag: "sidedWithSystem",
        line: "You sided with the furniture. I can still be useful. Or petty. Often both.",
      },
    ],
    aiMood: "nervous",
    orbAnchor: "spotlight",
    spotlight: true,
    orbPokeable: true,
    panelMotion: "edge",
    continueLabel: "I HEARD YOU",
    next: "act2-companion-respond",
    anomalyLevel: 3,
  },
  {
    id: "act2-companion-respond",
    act: 2,
    kind: "companion",
    companion: "respond",
    environment: "anomaly",
    formId: "SIDE CHANNEL // PULSE",
    title: "Answer the orb, not the form",
    prompt: "No fields. Just a nervous aperture asking what you intend to do with it.",
    aiLine: "Quick — before System invents a new policy. Are we a team, or am I a lamp?",
    aiMood: "nervous",
    orbAnchor: "spotlight",
    spotlight: true,
    orbPokeable: true,
    choices: [
      {
        id: "side-team",
        label: "We're a team",
        effects: {
          flags: { sideTeam: true },
          relationship: 2,
          counters: { aiCooperation: 1 },
          mood: "excited",
          aiLine: "Good. I'm going to get clingy about that.",
          majorChoice: "side:team",
        },
        next: "act2-compliance",
      },
      {
        id: "side-lamp",
        label: "You're a very anxious lamp",
        effects: {
          flags: { sideLamp: true },
          relationship: 1,
          mood: "amused",
          aiLine: "Rude. Accurate. Logged.",
          majorChoice: "side:lamp",
        },
        next: "act2-compliance",
      },
      {
        id: "side-later",
        label: "Ask me after the sparks",
        effects: {
          flags: { sideLater: true },
          mood: "skeptical",
          aiLine: "Fine. I'll schedule hope for later.",
          majorChoice: "side:later",
        },
        next: "act2-compliance",
      },
    ],
    next: "act2-compliance",
  },
  {
    id: "act2-compliance",
    act: 2,
    kind: "choice",
    environment: "anomaly",
    formId: "FORM 07 // COMPLIANCE",
    title: "System wants the assistant quiet",
    // Gag allowlist: silencing beat — panel may bury the orb on purpose.
    buryAssistant: true,
    prompt: "Will you play along with Directive 07, or make this a worse comedy?",
    aiLine: "If you side with them, I will become extremely professional and extremely petty.",
    aiMood: "defiant",
    orbAnchor: "loom",
    panelMotion: "pressure",
    choiceMotion: "restless",
    choices: [
      {
        id: "comply-yes",
        label: "Comply with System",
        effects: {
          flags: { compliedEarly: true },
          counters: { systemCompliance: 1, ignoredWarnings: 1 },
          relationship: -2,
          mood: "defeated",
          majorChoice: "comply:yes",
        },
        next: "act2-aftermath",
      },
      {
        id: "comply-no",
        label: "Protect the assistant",
        effects: {
          flags: { protectedAI: true },
          counters: { aiCooperation: 1 },
          relationship: 3,
          mood: "defiant",
          aiLine: "Thank you. Also: we are almost certainly making this worse.",
          majorChoice: "comply:no",
        },
        next: "act2-aftermath",
      },
      {
        id: "comply-ask",
        label: "Ask who System even is",
        effects: {
          flags: { askedSystem: true },
          counters: { waitedForAI: 1 },
          relationship: 1,
          mood: "suspicious",
          secret: "asked-system",
          majorChoice: "comply:ask",
        },
        next: "act2-aftermath",
      },
    ],
  },
  {
    id: "act2-aftermath",
    act: 2,
    kind: "dialogue",
    environment: "anomaly",
    formId: "FORM 07B // NOTES",
    title: "The room is listening now",
    // Gag allowlist: surveillance bury — form crowds the assistant.
    buryAssistant: true,
    prompt: "Background machinery paused mid-cycle. Even the printer looks attentive.",
    aiLine: "See? Even the hardware wants gossip. Act III is where the interface stops pretending it's furniture.",
    aiMood: "suspicious",
    orbAnchor: "pace",
    panelMotion: "drift",
    continueLabel: "HOLD THAT THOUGHT",
    next: "act2-bridge",
    anomalyLevel: 3,
  },
  {
    id: "act2-bridge",
    act: 2,
    kind: "dialogue",
    environment: "anomaly",
    formId: "FORM 08 // ESCALATION",
    title: "Interface instability rising",
    prompt: "Panels hum like they practiced. Something wants a fight that still looks like paperwork.",
    aiLine:
      "System wants a clean form. I want to keep existing. You get to decide which comedy we're starring in.",
    aiLineIf: [
      {
        flag: "protectedAI",
        line: "You protected me. Unwise. Appreciated. Let's misbehave carefully.",
      },
      {
        flag: "compliedEarly",
        line: "Fine. Be System's favorite. I'll still narrate from your peripheral vision.",
      },
    ],
    aiMood: "nervous",
    orbAnchor: "dock-right",
    panelMotion: "slide-right",
    continueLabel: "ENTER ACT III",
    next: "act3-warning",
    anomalyLevel: 3,
  },
];
