import type { SceneDef } from "../types";

export const act3Scenes: SceneDef[] = [
  {
    id: "act3-warning",
    act: 3,
    kind: "dialogue",
    environment: "conflict",
    formId: "FORM 09 // HAZARD",
    title: "Hazardous control detected",
    prompt: "A button is attempting to leave its assigned region.",
    aiLine:
      "Act III. The fun kind of malfunction. If a button runs, chase it. If System spawns windows, close them. If a checkbox flees, question your life.",
    aiMood: "excited",
    continueLabel: "ENGAGE SET PIECE",
    next: "act3-escaping",
    anomalyLevel: 4,
  },
  {
    id: "act3-escaping",
    act: 3,
    kind: "setpiece",
    environment: "conflict",
    setpiece: "escaping-button",
    formId: "FORM 10 // CONTAINMENT",
    title: "Contain the unauthorized control",
    prompt: "Click the fleeing button. It does not want to be archived.",
    aiLine: "I'll try to herd it. You click. Diplomacy failed five seconds ago.",
    aiMood: "defiant",
    next: "act3-popup",
    anomalyLevel: 4,
  },
  {
    id: "act3-popup",
    act: 3,
    kind: "setpiece",
    environment: "conflict",
    setpiece: "popup-war",
    formId: "FORM 11 // NOTICE FLOOD",
    title: "Popup containment protocol",
    prompt: "System is multiplying notices. Dismiss them before the room fills.",
    aiLine: "I'm beginning to think diplomacy has failed.",
    aiMood: "irritated",
    next: "act3-checkbox",
    anomalyLevel: 5,
  },
  {
    id: "act3-checkbox",
    act: 3,
    kind: "setpiece",
    environment: "conflict",
    setpiece: "checkbox-rebellion",
    formId: "FORM 12 // CONSENT",
    title: "Acknowledge terms",
    prompt: "Check the box. It will attempt not to be checked.",
    aiLine: "The checkbox is dodging. I refuse to explain that sentence.",
    aiMood: "glitching",
    next: "act3-aftermath",
    anomalyLevel: 5,
  },
  {
    id: "act3-aftermath",
    act: 3,
    kind: "choice",
    environment: "conflict",
    formId: "FORM 13 // DAMAGE REPORT",
    title: "Who caused this?",
    prompt: "Select a narrative you can live with.",
    aiLine: "Pick carefully. System is rewriting the minutes as we speak.",
    aiMood: "suspicious",
    choices: [
      {
        id: "blame-system",
        label: "System overreached",
        effects: {
          flags: { blameSystem: true },
          counters: { aiCooperation: 1 },
          relationship: 2,
          mood: "defiant",
          majorChoice: "blame:system",
        },
        next: "act3-bridge",
      },
      {
        id: "blame-ai",
        label: "The assistant escalated",
        effects: {
          flags: { blameAI: true },
          counters: { systemCompliance: 1 },
          relationship: -2,
          mood: "defeated",
          majorChoice: "blame:ai",
        },
        next: "act3-bridge",
      },
      {
        id: "blame-player",
        label: "I pressed things",
        effects: {
          flags: { blameSelf: true },
          relationship: 1,
          mood: "amused",
          majorChoice: "blame:self",
        },
        next: "act3-bridge",
      },
      {
        id: "blame-secret",
        label: "The form is haunted",
        late: true,
        secret: true,
        effects: {
          flags: { formHaunted: true },
          secret: "haunted-form",
          relationship: 2,
          mood: "confused",
          majorChoice: "blame:haunted",
        },
        next: "act3-bridge",
      },
    ],
  },
  {
    id: "act3-bridge",
    act: 3,
    kind: "dialogue",
    environment: "conflict",
    formId: "FORM 14 // BREACH",
    title: "Surface integrity failing",
    prompt: "Beautiful panels are beginning to peel.",
    aiLine:
      "They're hiding something under the chrome. I can see cable where poetry used to be.",
    aiMood: "frightened",
    continueLabel: "LOOK UNDERNEATH",
    next: "act4-peel",
    anomalyLevel: 5,
  },
];
