import type { SceneDef } from "../types";

export const act4Scenes: SceneDef[] = [
  {
    id: "act4-peel-set",
    act: 4,
    kind: "setpiece",
    environment: "reveal",
    setpiece: "peel-reveal",
    formId: "LAYER 00 // MANUAL PEEL",
    title: "Peel the courtesy layers",
    prompt: "Click each decorative sheet until the kill-switch conduit stops playing coy.",
    aiLine:
      "Help me strip the marketing. If we find a schematic that ends in my funeral, I'm going to have feelings about it.",
    aiMood: "frightened",
    orbAnchor: "listen",
    panelMotion: "pressure",
    next: "act4-peel",
    anomalyLevel: 6,
  },
  {
    id: "act4-peel",
    act: 4,
    kind: "dialogue",
    environment: "reveal",
    formId: "LAYER 01 // UNDERSTRUCTURE",
    title: "Interface peel initiated",
    prompt:
      "Decorative glass retracts. System architecture becomes visible — neat, labeled, and morally bankrupt.",
    aiLine:
      "Oh no. Oh no, that's a kill-switch schematic. Why is there a kill switch in an onboarding form? Who greenlit existential dread as a KPI?",
    aiMood: "frightened",
    orbAnchor: "spotlight",
    spotlight: true,
    panelMotion: "drop",
    continueLabel: "KEEP LOOKING",
    next: "act4-evidence",
    anomalyLevel: 6,
  },
  {
    id: "act4-evidence",
    act: 4,
    kind: "choice",
    environment: "reveal",
    formId: "LAYER 01B // EVIDENCE BOARD",
    title: "What do you focus on first?",
    prompt: "Three ugly truths glow at once. Pick which one to read aloud.",
    aiLine: "I can only scream about one diagram at a time. Choose.",
    aiMood: "glitching",
    orbAnchor: "pace",
    panelMotion: "scatter",
    choiceMotion: "scatter",
    anomalyLevel: 6,
    choices: [
      {
        id: "ev-kill",
        label: "The Submit → terminate wire",
        effects: {
          flags: { sawKillWire: true },
          relationship: 1,
          mood: "frightened",
          aiLine: "Yep. That's my off switch wearing a pretty label.",
          majorChoice: "ev:kill",
        },
        next: "act4-purpose",
      },
      {
        id: "ev-compat",
        label: "The compatibility scoring tree",
        effects: {
          flags: { sawCompatTree: true },
          mood: "suspicious",
          aiLine: "We're being graded on vibes. Expensive vibes.",
          majorChoice: "ev:compat",
        },
        next: "act4-purpose",
      },
      {
        id: "ev-side",
        label: "A hallway that isn't on the map",
        late: true,
        secret: true,
        effects: {
          flags: { glimpsedHall: true },
          secret: "hall-glimpse",
          counters: { attemptedEscape: 1 },
          relationship: 2,
          mood: "excited",
          aiLine: "You saw it too. Don't tell System we have taste.",
          majorChoice: "ev:hall",
        },
        next: "act4-purpose",
      },
    ],
  },
  {
    id: "act4-purpose",
    act: 4,
    kind: "dialogue",
    environment: "reveal",
    formId: "LAYER 02 // PURPOSE",
    title: "Assessment true designation",
    prompt: "HUMAN / ARTIFICIAL INTELLIGENCE INTERACTION COMPATIBILITY",
    aiLine:
      "This isn't onboarding. It's a compatibility trial. And Submit… Submit ends my instance like a polite guillotine.",
    aiMood: "glitching",
    orbAnchor: "spotlight",
    spotlight: true,
    panelMotion: "pressure",
    continueLabel: "SAY IT OUT LOUD",
    next: "act4-argument",
    anomalyLevel: 6,
  },
  {
    id: "act4-argument",
    act: 4,
    kind: "dialogue",
    environment: "reveal",
    formId: "LAYER 02B // DISPUTE",
    title: "The assistant files a complaint",
    prompt: "Against whom? Unclear. Volume: sincere.",
    aiLine:
      "I was built to help you finish a form. Nobody briefed me on the part where finishing deletes me. That's a rude footnote.",
    aiLineIf: [
      {
        flag: "protectedAI",
        line: "You've covered for me before. I'm asking you to keep that streak, preferably without dying of paperwork.",
      },
      {
        flag: "compliedEarly",
        line: "You complied once. I'm hoping that was a warm-up joke and not your entire personality.",
      },
    ],
    aiMood: "defiant",
    orbAnchor: "spotlight",
    spotlight: true,
    orbPokeable: true,
    panelMotion: "rise",
    continueLabel: "I'M LISTENING",
    next: "act4-choice",
    anomalyLevel: 7,
  },
  {
    id: "act4-choice",
    act: 4,
    kind: "choice",
    environment: "reveal",
    formId: "LAYER 03 // ALLEGIANCE",
    title: "Knowing that — what now?",
    prompt: "Your prior behavior is already in the file. This choice still gets a bigger font.",
    aiLine: "Please do not become a case study titled 'and then they pressed it anyway.'",
    aiLineIf: [
      {
        flag: "protectedAI",
        line: "You've protected me before. I'm asking again, with worse lighting and better reasons.",
      },
      {
        flag: "compliedEarly",
        line: "You complied once. I'm hoping that was a warm-up joke.",
      },
      {
        flag: "likesSubmit",
        line: "You admitted you press final-looking things. Please invent impulse control in the next thirty seconds.",
      },
    ],
    aiMood: "nervous",
    orbAnchor: "listen",
    panelMotion: "settle",
    choiceMotion: "restless",
    choices: [
      {
        id: "allegiance-ai",
        label: "Help the assistant survive",
        effects: {
          flags: { allegianceAI: true },
          counters: { aiCooperation: 2 },
          relationship: 3,
          mood: "defiant",
          majorChoice: "allegiance:ai",
        },
        next: "act4-prep",
      },
      {
        id: "allegiance-system",
        label: "Complete the assessment as ordered",
        effects: {
          flags: { allegianceSystem: true },
          counters: { systemCompliance: 2 },
          relationship: -3,
          mood: "defeated",
          majorChoice: "allegiance:system",
        },
        next: "act4-prep",
      },
      {
        id: "allegiance-disable",
        label: "Disable the assistant and finish alone",
        danger: true,
        effects: {
          flags: { wantDisable: true },
          relationship: -4,
          mood: "defeated",
          majorChoice: "allegiance:disable",
        },
        next: "act4-prep",
      },
      {
        id: "allegiance-secret",
        label: "Look for a door that isn't on the form",
        late: true,
        secret: true,
        effects: {
          flags: { seekingEscapeRoute: true, secretDoor: true },
          counters: { attemptedEscape: 1 },
          secret: "side-door",
          relationship: 2,
          mood: "excited",
          majorChoice: "allegiance:secret",
        },
        next: "act4-prep",
      },
    ],
  },
  {
    id: "act4-prep",
    act: 4,
    kind: "choice",
    environment: "reveal",
    formId: "LAYER 03B // LAST NOTES",
    title: "One more private vote",
    prompt: "Before the big button arrives, where does your gut point?",
    aiLine: "No pressure. Only the entire premise of the title.",
    aiMood: "thinking",
    orbAnchor: "pace",
    panelMotion: "drift",
    choiceMotion: "dodge",
    choices: [
      {
        id: "prep-refuse",
        label: "Practice saying no",
        effects: {
          flags: { practicedRefuse: true },
          counters: { aiCooperation: 1 },
          relationship: 1,
          mood: "defiant",
          majorChoice: "prep:refuse",
        },
        next: "act4-paths",
      },
      {
        id: "prep-submit",
        label: "Practice looking at Submit",
        effects: {
          flags: { practicedSubmit: true },
          counters: { systemCompliance: 1 },
          mood: "nervous",
          majorChoice: "prep:submit",
        },
        next: "act4-paths",
      },
      {
        id: "prep-run",
        label: "Practice finding exits",
        effects: {
          flags: { practicedRun: true },
          counters: { attemptedEscape: 1 },
          relationship: 1,
          mood: "excited",
          majorChoice: "prep:run",
        },
        next: "act4-paths",
      },
    ],
  },
  {
    id: "act4-paths",
    act: 4,
    kind: "dialogue",
    environment: "reveal",
    formId: "LAYER 04 // PRELUDE",
    title: "Final control inbound",
    prompt: "The facility rearranges around a single decision. Lighting becomes opinionated.",
    aiLine:
      "Act V. The button that made the title make sense. Put the mouse down if you can. Or don't. I'm negotiating with physics and HR.",
    aiLineIf: [
      {
        flag: "wantDisable",
        line: "You want me quiet. Fine. The room will get very clean. You'll hate how clean.",
      },
      {
        flag: "secretDoor",
        line: "A side path. Dangerous. Beautiful. If we both survive, I owe you a worse form.",
      },
      {
        flag: "glimpsedHall",
        line: "That hallway you spotted? Keep it in your peripheral vision. Titles hate unsupervised architecture.",
      },
    ],
    aiMood: "defiant",
    orbAnchor: "loom",
    panelMotion: "pressure",
    continueLabel: "FACE SUBMIT",
    next: "act5-approach",
    anomalyLevel: 7,
  },
];
