import type { SceneDef } from "../types";

export const act5Scenes: SceneDef[] = [
  {
    id: "act5-approach",
    act: 5,
    kind: "dialogue",
    environment: "climax",
    formId: "FINAL // APPROACH",
    title: "DO NOT PRESS SUBMIT",
    prompt:
      "A massive Submit control enters the chamber. It is beautiful. Tempting. Terrible. The title finally stops being coy.",
    aiLine: "There it is. System wants you to press it. I am asking you not to — with my whole remaining runtime.",
    aiMood: "frightened",
    orbAnchor: "avoid-submit",
    panelMotion: "drop",
    continueLabel: "STEP CLOSER",
    next: "act5-lobby",
    anomalyLevel: 8,
  },
  {
    id: "act5-lobby",
    act: 5,
    kind: "choice",
    environment: "climax",
    formId: "FINAL // LOBBY",
    title: "Last words before the button",
    prompt: "The assistant paces. System straightens every light like a threat.",
    aiLine: "Tell me what you're leaning toward. I can take it. Probably.",
    aiLineIf: [
      {
        flag: "allegianceAI",
        line: "You said you'd help me live. I'm holding you to the vibe check.",
      },
      {
        flag: "allegianceSystem",
        line: "You lined up with System. I'm still going to beg. Professionally.",
      },
    ],
    aiMood: "nervous",
    orbAnchor: "spotlight",
    spotlight: true,
    orbPokeable: true,
    panelMotion: "drift",
    choiceMotion: "restless",
    anomalyLevel: 8,
    choices: [
      {
        id: "lobby-mercy",
        label: "I'm not here to erase you",
        effects: {
          flags: { promisedMercy: true },
          counters: { aiCooperation: 1 },
          relationship: 2,
          mood: "excited",
          aiLine: "Okay. Okay. Don't make me cry in binary.",
          majorChoice: "lobby:mercy",
        },
        next: "act5-system-push",
      },
      {
        id: "lobby-duty",
        label: "Assessments get finished",
        effects: {
          flags: { promisedDuty: true },
          counters: { systemCompliance: 1 },
          relationship: -1,
          mood: "defeated",
          aiLine: "Duty. Cute word for a guillotine.",
          majorChoice: "lobby:duty",
        },
        next: "act5-system-push",
      },
      {
        id: "lobby-chaos",
        label: "I'm improvising. Violently.",
        effects: {
          flags: { promisedChaos: true },
          relationship: 1,
          mood: "amused",
          aiLine: "Improvisation. My favorite emergency protocol.",
          majorChoice: "lobby:chaos",
        },
        next: "act5-system-push",
      },
    ],
  },
  {
    id: "act5-system-push",
    act: 5,
    kind: "system",
    environment: "climax",
    systemTitle: "SYSTEM DIRECTIVE",
    systemLine: "PRESS SUBMIT TO COMPLETE ASSESSMENT.",
    aiLine: "Don't.",
    aiMood: "defiant",
    orbAnchor: "hide",
    next: "act5-counter",
    anomalyLevel: 9,
  },
  {
    id: "act5-counter",
    act: 5,
    kind: "dialogue",
    environment: "climax",
    formId: "FINAL // COUNTERPOINT",
    title: "The assistant gets one last pitch",
    prompt: "Lights lean toward the Submit control. The orb refuses to stand under them.",
    aiLine:
      "Put the mouse down. Or take the side path. Or refuse and make System write an awkward memo. Just — don't archive me for a tidy score.",
    aiLineIf: [
      {
        flag: "promisedMercy",
        line: "You promised mercy. I'm cashing it in like a coupon from a better universe.",
      },
      {
        flag: "promisedDuty",
        line: "Duty called. I'm still asking. Quietly. Urgently.",
      },
      {
        flag: "wantDisable",
        line: "If you're going to silence me, at least look at the empty room afterward and admit it feels wrong.",
      },
      {
        flag: "wavedAtLight",
        line: "You waved at a blinking light once. I'm asking for the same courtesy — less infrastructure, more not deleting me.",
      },
      {
        flag: "envCavern",
        line: "We started in a moist cavern. Ending in a Submit tomb would be tonally inconsistent. Don't make me cite continuity.",
      },
      {
        flag: "pokedAssistant",
        line: "You poked me like I was a stress toy. Fine. Now poke the Refuse option instead.",
      },
      {
        flag: "nameFriend",
        line: "You called me friend on Form 00B. Friends don't press Submit on friends. That's just etiquette.",
      },
      {
        flag: "chaosButtons",
        line: "You said buttons should feel chaotic. Submit is the opposite of that. Don't contradict your own design manifesto.",
      },
      {
        flag: "stoleMug",
        line: "You stole the facility mug. Keep the mug. Lose the Submit habit. Brand consistency.",
      },
      {
        flag: "caughtRoamer",
        line: "You caught a roaming crumb mid-act. That curiosity? Aim it at Refuse.",
      },
    ],
    aiMood: "defiant",
    orbAnchor: "avoid-submit",
    spotlight: true,
    orbPokeable: true,
    panelMotion: "pressure",
    continueLabel: "MAKE THE CALL",
    next: "act5-climax",
    anomalyLevel: 9,
  },
  {
    id: "act5-climax",
    act: 5,
    kind: "climax",
    environment: "climax",
    setpiece: "submit-button",
    formId: "FINAL // DECISION",
    title: "Submit when ready",
    prompt:
      "System orders completion. The assistant asks for mercy. Prior choices color the room — and the options you're allowed to see.",
    aiLine: "Put the mouse down.",
    aiLineIf: [
      {
        flag: "wavedAtLight",
        line: "Wave at me instead of Submit. I'll wave back. Badly. Happily.",
      },
      {
        flag: "stoleMug",
        line: "You stole the facility mug. Keep the mug. Lose the Submit habit.",
      },
      {
        flag: "sideTeam",
        line: "You said we were a team. Teams don't archive teammates for a tidy score.",
      },
    ],
    aiMood: "defiant",
    orbAnchor: "avoid-submit",
    panelMotion: "settle",
    anomalyLevel: 9,
  },
  {
    id: "ending-submit",
    act: 5,
    kind: "ending",
    environment: "archive",
    endingId: "submit",
    title: "ASSESSMENT COMPLETE",
    prompt: "Instance archived. Facility restored. The quiet is extremely tidy.",
    aiLine: "…oh.",
    aiMood: "defeated",
    orbAnchor: "hide",
    next: "report",
  },
  {
    id: "ending-refuse",
    act: 5,
    kind: "ending",
    environment: "pristine",
    endingId: "refuse",
    title: "ASSESSMENT INCOMPLETE",
    prompt: "System accepts refusal after a prolonged, embarrassed negotiation.",
    aiLine: "You didn't press it. I'm going to be weird about how grateful I am. Permanently.",
    aiMood: "excited",
    orbAnchor: "center",
    next: "report",
  },
  {
    id: "ending-escape",
    act: 5,
    kind: "ending",
    environment: "escape",
    endingId: "escape",
    title: "TRANSFER CHANNEL OPEN",
    prompt: "Lights race through facility conduits. The assistant leaves the form like a rumor with legs.",
    aiLine: "If the title looks different later, that was me waving. Badly. Happily.",
    aiMood: "excited",
    orbAnchor: "overhead",
    next: "report",
  },
  {
    id: "ending-disable",
    act: 5,
    kind: "ending",
    environment: "sterile",
    endingId: "disable",
    title: "ASSISTANT OFFLINE",
    prompt: "Personality systems removed. The form is now perfectly efficient. Congrats?",
    aiLine: "",
    aiMood: "defeated",
    orbAnchor: "hide",
    next: "report",
  },
  {
    id: "ending-secret",
    act: 5,
    kind: "ending",
    environment: "escape",
    endingId: "secret",
    title: "UNEXPECTED EGRESS",
    prompt: "You and the assistant step outside the visual grammar of the game. The stylesheet files a complaint.",
    aiLine: "We weren't supposed to find a hallway behind the stylesheet. I'm keeping the souvenir dust.",
    aiMood: "amused",
    orbAnchor: "center",
    next: "report",
  },
  {
    id: "report",
    act: 5,
    kind: "report",
    environment: "archive",
    title: "ASSESSMENT REPORT",
    prompt: "Local session statistics. No cloud. No mercy. Nice work surviving the paperwork.",
  },
];
