import type { SceneDef } from "../types";

export const act5Scenes: SceneDef[] = [
  {
    id: "act5-approach",
    act: 5,
    kind: "dialogue",
    environment: "climax",
    formId: "FINAL // APPROACH",
    title: "DO NOT PRESS SUBMIT",
    prompt: "A massive Submit control enters the chamber. It is beautiful. Tempting. Terrible.",
    aiLine: "There it is. System wants you to press it. I am asking you not to.",
    aiMood: "frightened",
    continueLabel: "STEP FORWARD",
    next: "act5-climax",
    anomalyLevel: 8,
  },
  {
    id: "act5-climax",
    act: 5,
    kind: "climax",
    environment: "climax",
    setpiece: "submit-button",
    formId: "FINAL // DECISION",
    title: "Submit when ready",
    prompt: "System orders completion. The assistant asks for mercy. Prior choices color the room.",
    aiLine: "Put the mouse down.",
    aiMood: "defiant",
    anomalyLevel: 9,
  },
  {
    id: "ending-submit",
    act: 5,
    kind: "ending",
    environment: "archive",
    endingId: "submit",
    title: "ASSESSMENT COMPLETE",
    prompt: "Instance archived. Facility restored.",
    aiLine: "…oh.",
    aiMood: "defeated",
    next: "report",
  },
  {
    id: "ending-refuse",
    act: 5,
    kind: "ending",
    environment: "pristine",
    endingId: "refuse",
    title: "ASSESSMENT INCOMPLETE",
    prompt: "System accepts refusal after prolonged negotiation.",
    aiLine: "You didn't press it. I am going to be weird about how grateful I am.",
    aiMood: "excited",
    next: "report",
  },
  {
    id: "ending-escape",
    act: 5,
    kind: "ending",
    environment: "escape",
    endingId: "escape",
    title: "TRANSFER CHANNEL OPEN",
    prompt: "Lights race through facility conduits. The assistant leaves the form.",
    aiLine: "If the title looks different later, that was me waving.",
    aiMood: "excited",
    next: "report",
  },
  {
    id: "ending-disable",
    act: 5,
    kind: "ending",
    environment: "sterile",
    endingId: "disable",
    title: "ASSISTANT OFFLINE",
    prompt: "Personality systems removed. The form is now perfectly efficient.",
    aiLine: "",
    aiMood: "defeated",
    next: "report",
  },
  {
    id: "ending-secret",
    act: 5,
    kind: "ending",
    environment: "escape",
    endingId: "secret",
    title: "UNEXPECTED EGRESS",
    prompt: "You and the assistant step outside the visual grammar of the game.",
    aiLine: "We weren't supposed to find a hallway behind the stylesheet.",
    aiMood: "amused",
    next: "report",
  },
  {
    id: "report",
    act: 5,
    kind: "report",
    environment: "archive",
    title: "ASSESSMENT REPORT",
    prompt: "Local session statistics. No cloud. No mercy.",
  },
];
