/**
 * Build-time baked VO stubs (P1 #9).
 *
 * Writes short character-ish WAV takes per line ID × mood into public/audio/vo/.
 * No runtime speechSynthesis. No cloud TTS API.
 *
 * These are PLACEHOLDER takes (additive formant stubs) so playback plumbing
 * can ship before real recorded VO / neural bake. Re-run anytime:
 *   node scripts/bake-voice.mjs
 *
 * Wired from npm run predev / prebuild.
 */
import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const outDir = join(root, "public", "audio", "vo");

/** @typedef {"calm"|"petty"|"alarmed"} VoiceMood */

const MOODS = /** @type {const} */ (["calm", "petty", "alarmed"]);

/** Hero beats — real VO targets; stubs for now. */
const HERO_IDS = [
  "hero-title",
  "hero-system-override",
  "hero-ending-submit",
  "hero-ending-refuse",
  "hero-ending-escape",
  "hero-ending-disable",
  "hero-ending-secret",
];

/** High-volume poke banter buckets (text hashed → poke-NN at runtime). */
const POKE_COUNT = 24;

/** A few high-traffic scene IDs so Act I / climax dialogue has audio. */
const SCENE_IDS = [
  "scene-act1-welcome",
  "scene-act1-name",
  "scene-act1-honesty",
  "scene-act5-approach",
  "scene-act5-climax",
];

function hashSeed(str) {
  let h = 2166136261 >>> 0;
  for (let i = 0; i < str.length; i++) {
    h ^= str.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

function moodParams(mood) {
  switch (mood) {
    case "petty":
      return { base: 196, buzz: 0.55, rate: 1.12, bright: 1.25, dur: 0.72 };
    case "alarmed":
      return { base: 240, buzz: 0.85, rate: 1.28, bright: 1.45, dur: 0.58 };
    default:
      return { base: 168, buzz: 0.35, rate: 0.95, bright: 1.0, dur: 0.9 };
  }
}

/** Synthetic “character voice” stub — not intelligible speech; distinct per id/mood. */
function synthesizePcm(lineId, mood) {
  const p = moodParams(mood);
  const seed = hashSeed(`${lineId}::${mood}`);
  const sampleRate = 22050;
  const duration = p.dur + ((seed % 17) / 100);
  const n = Math.floor(sampleRate * duration);
  const data = new Float32Array(n);

  const f0 = p.base + (seed % 37);
  const f1 = f0 * 2.15;
  const f2 = f0 * 3.4 * p.bright;
  const syllables = 4 + (seed % 5);

  for (let i = 0; i < n; i++) {
    const t = i / sampleRate;
    const env =
      Math.min(1, t * 18) *
      Math.min(1, (duration - t) * 10) *
      (0.55 + 0.45 * Math.sin(2 * Math.PI * syllables * (t / duration) * p.rate));
    const buzz = Math.sin(2 * Math.PI * f0 * t * p.rate);
    const form =
      0.55 * buzz +
      0.28 * Math.sin(2 * Math.PI * f1 * t * p.rate + buzz * p.buzz) +
      0.12 * Math.sin(2 * Math.PI * f2 * t) +
      0.05 * (((seed >> (i % 8)) & 1) * 2 - 1) * p.buzz;
    data[i] = form * env * 0.28;
  }
  return { sampleRate, data };
}

function floatToWav(sampleRate, data) {
  const numChannels = 1;
  const bitsPerSample = 16;
  const blockAlign = (numChannels * bitsPerSample) / 8;
  const byteRate = sampleRate * blockAlign;
  const dataSize = data.length * blockAlign;
  const buffer = Buffer.alloc(44 + dataSize);
  buffer.write("RIFF", 0);
  buffer.writeUInt32LE(36 + dataSize, 4);
  buffer.write("WAVE", 8);
  buffer.write("fmt ", 12);
  buffer.writeUInt32LE(16, 16);
  buffer.writeUInt16LE(1, 20);
  buffer.writeUInt16LE(numChannels, 22);
  buffer.writeUInt32LE(sampleRate, 24);
  buffer.writeUInt32LE(byteRate, 28);
  buffer.writeUInt16LE(blockAlign, 32);
  buffer.writeUInt16LE(bitsPerSample, 34);
  buffer.write("data", 36);
  buffer.writeUInt32LE(dataSize, 40);
  for (let i = 0; i < data.length; i++) {
    const s = Math.max(-1, Math.min(1, data[i]));
    buffer.writeInt16LE((s * 32767) | 0, 44 + i * 2);
  }
  return buffer;
}

function writeTake(lineId, mood) {
  const { sampleRate, data } = synthesizePcm(lineId, mood);
  const wav = floatToWav(sampleRate, data);
  const file = join(outDir, `${lineId}--${mood}.wav`);
  writeFileSync(file, wav);
  return file;
}

mkdirSync(outDir, { recursive: true });

const ids = [
  ...HERO_IDS,
  ...SCENE_IDS,
  ...Array.from({ length: POKE_COUNT }, (_, i) => `poke-${String(i).padStart(2, "0")}`),
];

let written = 0;
for (const id of ids) {
  for (const mood of MOODS) {
    writeTake(id, mood);
    written += 1;
  }
}

const manifest = {
  generatedAt: new Date().toISOString(),
  format: "wav",
  moods: [...MOODS],
  lineIds: ids,
  notes:
    "Stub character takes (formant synthesis). Replace with recorded VO or neural bake; keep filenames {lineId}--{mood}.wav",
};
writeFileSync(join(outDir, "manifest.json"), JSON.stringify(manifest, null, 2) + "\n");

const readme = `# Baked VO stubs

Generated by \`node scripts/bake-voice.mjs\` (also \`predev\` / \`prebuild\`).

- **Hero:** \`hero-title\`, \`hero-system-override\`, \`hero-ending-*\`
- **Banter:** \`poke-00\` … \`poke-23\` (runtime hashes poke text → bucket)
- **Moods:** calm / petty / alarmed → \`{lineId}--{mood}.wav\`

No live \`speechSynthesis\`. No runtime cloud TTS.
Replace stubs with real recorded VO when assets land; keep the filename contract.
`;
writeFileSync(join(outDir, "README.md"), readme);

console.log(
  `bake-voice: wrote ${written} takes + manifest → ${existsSync(outDir) ? "public/audio/vo" : outDir}`,
);
